project:
  type: website

website:
  title: "UC 6132 - FENÔMENOS ELETROMAGNÉTICOS"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: cronograma.qmd
        text: Cronograma / Materiais

      - href: plano-de-ensino.qmd
        text: Plano de Ensino

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: false